language: r

matrix:
  include:
    - r: oldrel
      os: linux
      dist: trusty
      sudo: false

warnings_are_errors: true

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()' || echo "non-release build"

before_script:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e "utils::install.packages('covr')" || echo "non-release build"

