language: r
sudo: false
latex: false

matrix:
  include:
    - r: oldrel
      os: linux
    - r: release
      os: linux
    - r: release
      os: osx

addons:
  apt_packages:
    - pandoc

notifications:
  email:
    on_success: change
    on_failure: change
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - BOOTSTRAP_LATEX=1
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran"
